const lang = {
    'Reviews': 'Reviews',
    'Customer Care': 'Customer Care',
    'Resolution Center': 'Resolution Center',
    'Inbox': 'Inbox',
    'NOTE_REGISTER_TITLE': 'Register',
    'Home': 'Home',
    'Purchase': 'Purchase',
    'Sign Out': 'Sign Out',
    'Open Shop': 'Open Shop',
    'Cancelled Order': 'Cancelled Order',
    'Confirm Payment': 'Payment Confirmation',
    'Order Status': 'Order Status',
    'Dispute List': 'Transaction List',
    'New Order': 'New Order',
    'Confirm Shipment': 'Shipping Confirmation',
    'Product Shipping Status': 'Shipping Status',
    'Transaction Status': 'Transaction List',
    'Product List': 'Product List',
    'QUICK_GUIDE_SHOP_GOLD_TITLE_9': 'Shop Showcase',
    'Choose Language': 'Choose Language',
    'Desktop Site': 'Desktop Site',
    'Need Help': 'Need Help',
    'MESSAGE': 'Message',
    'Talk About It': 'Talk About It',
    'Sales': 'Sales',
    'Login': 'Login',
    'Why Buy on Tokopedia': 'Why Buy on Tokopedia',
    'Why Sell on Tokopedia': 'Why Sell on Tokopedia',
    'RESERVE_TRAIN_TICKET': 'Reserve Train Ticket',
    'BUY_RECHARGE': 'Refill Phone Balance',
    'Events': 'Events',
    'About Us': 'About Us',
    'Career': 'Career',
    'term & condition': 'Term & Conditions',
    'Privacy Policy': 'Privacy Policy',
    'Contact Us': 'Contact Us',
    'Download Tokopedia Mobile Apps': 'Download Tokopedia Mobile Apps',
    'Search Products or Stores': 'Search products or stores',
    'View All Promo': 'View All Promo',
    'Pulsa': 'Buy Recharge',
    'Saldo': 'Balance',
    'Paket Data': 'Data Plan',
    'Listrik': 'Electricity',
    'Tiket': 'Ticket',
    'Dapur': 'Kitchen',
    'Otomotif': 'Automotive',
    'Rumah Tangga': 'House Hold',
    'Kecantikan': 'Beauty',
    'Kesehatan': 'Health',
    'Fashion & Aksesoris': 'Fashion & Accessories',
    'Olahraga': 'Sports',
    'Fashion Anak': 'Kids Fashion',
    'Kamera, Foto & Video': 'Camera, Photo & Video',
    'Komputer & Aksesoris': 'Computer & Accessories',
    'Handphone & Tablet': 'Handphone & Tablet',
    'Elektronik': 'Electronic',
    'Software': 'Software',
    'Laptop & Aksesoris': 'Laptop & Accessories',
    'Souvenir, Kado & Hadiah': 'Souvenirs & Gift',
    'Buku': 'Books',
    'Office & Stationery': 'Office & Stationery',
    'Film, Musik & Game': 'Film, Music & Game',
    'Ibu & Bayi': 'Mom & Baby',
    'Makanan & Minuman': 'Foods & Drinks',
    'Produk Lainnya': 'Others Product',
    'View More': 'Load More',
    'Toko Saya': 'My Shop',
    'Mainan & Hobi': 'Toys & Hobby',
    'Fashion Pria': 'Men Fashion',
    'Fashion Wanita': 'Women Fashion',
    'Fashion Muslim': 'Muslim Fashion',
    'Kamera': 'Camera',
    'Lihat Semua Hotlist': 'View All Hotlists',
    'Aktivasi TokoCash': 'Activate TokoCash',
    'Lihat Semua': 'View All',
    'Hapus Semua': 'Clear All',
    'Mulai dari': 'Starts from',
    'Kartu Kredit': 'Credit Card',
    'Search in Wishlist': 'Search product in wishlist',
    'Empty wishlist': 'Your Wishlish is empty',
    'Buy': 'Buy',
    'Add Wishlist Success': 'You just added :item into your wishlist',
    'Add Wishlist Failed': 'Failed adding :item to wishlist',
    'Remove Wishlist Success': 'You just removed :item from your wishlist',
    'Remove Wishlist Failed': 'Failed removing :item from wishlist',
    'Teknologi': 'Technology',
    'Kategori Lain': 'Others',
    'Gaya Hidup': 'Lifestyle',
    'Pembayaran & Top Up': 'Payment & Top Up',
    'Pakaian': 'Outfit',
    'Perawatan Bayi': 'Baby Care',
    'Pascabayar': 'Postpaid',
    'Hasil': 'Result',
    'Delivery Confirm': 'Receive Confirmation',
    'Search for Products': 'Search for Products',
    'Out of Stock': 'Out of Stock',
    'Clear': 'Clear',
    'Wishlist Search Empty': 'No matching product found',
    'See All Wishlists': 'See All Products',
    'Search Shop in Favorite': 'Search shops in favorite list',
    'Cari lokasi': 'Search Location',
    'TERAKHIR DILIHAT': 'RECENTLY VIEWED',
    'INSPIRASI DARI MINAT ANDA' :'RELATED TO ITEMS YOU\'VE VIEWED',
    'INSPIRASI DARI WISHLIST' : 'INSPIRED BY YOUR WISHLIST',
    'INSPIRASI DARI PEMBELIAN' : 'INSPIRED BY YOUR PURCHASED',
    'PRODUCT FEED' : 'PRODUCT FEED'
}

module.exports = lang
